apiVersion: v1
kind: Service
metadata:
  name: mlops-service
  labels:
    app: mlops-app
spec:
  type: LoadBalancer
  selector:
    app: mlops-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000